### ISSUE TITLE
booksサブコマンドがCP932にエンコードできない文字があると落ちる

### ISSUE THREAD

**Issue by mtsukamoto** [aozorahack/aozora-cli#14]
booksサブコマンドをWindows環境、引数なしで実行するとエラーが起きました。
エラーメッセージから、返ってきたデータ中にCP932にエンコードできない文字があって落ちたのかな、と思いました。

```
C:\Users\tsukamoto\temp\aozora-cli>python ./bin/aozora books
Traceback (most recent call last):
(略）
 File "C:\Users\ap745667\temp\aozora-cli\aozoracli\cli.py", line 19, in books
   'title': title,
 File "C:\Users\ap745667\temp\aozora-cli\aozoracli\books.py", line 21, in main
   print(books)
UnicodeEncodeError: 'cp932' codec can't encode character '\xd6' in position 88210: illegal multibyte sequence
```

Windows固有（CLIがCP932）の気もするので、後回しでいいかも。

**Comment by yasuhiroki** [comment]
おおお.....(汗
試せていませんが、デフォルトエンコーディングをutf8にすれば解決できないでしょうか...

http://yukihir0.hatenablog.jp/entry/20110131/1296478348
