### ISSUE TITLE
pip installでのエラー

### ISSUE THREAD

**Issue by ksato9700** [aozorahack/aozora-cli#21]
pipでのインストールを試みましたが、以下の様なエラーが出てしまいます。

```
$ pip install aozora-cli
Collecting aozora-cli
  Using cached aozora-cli-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jj/8dwknd5x75z2g4czzvshkfwc0000gn/T/pip-build-53ydt4x7/aozora-cli/setup.py", line 7, in <module>
        import aozoracli.version
      File "/private/var/folders/jj/8dwknd5x75z2g4czzvshkfwc0000gn/T/pip-build-53ydt4x7/aozora-cli/aozoracli/__init__.py", line 1, in <module>
        from .cli import *
      File "/private/var/folders/jj/8dwknd5x75z2g4czzvshkfwc0000gn/T/pip-build-53ydt4x7/aozora-cli/aozoracli/cli.py", line 2, in <module>
        import click
    ImportError: No module named 'click'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jj/8dwknd5x75z2g4czzvshkfwc0000gn/T/pip-build-53ydt4x7/aozora-cli/
```

おそらく、setup.py内でversionを参照するのに`aozoracli.version`をimportしているのが原因かと思います。そのimport時に__init.py__経由でcli.pyをimportし、そこに書かれているimport clickが実行出来ずに落ちているように見えます。残念ながら install_requiresに依存関係として書いていてもダメなようです。

解決するのは、例えば

```
--- a/setup.py
+++ b/setup.py
@@ -4,11 +4,11 @@
 from setuptools import setup, find_packages
 import os

-import aozoracli.version
+exec(open('aozoracli/version.py').read())

 setup(
     name='aozora-cli',
-    version=aozoracli.version.__version__,
+    version=__version__,
     description='Aozora Bunko Command Line Tool',
     author='Yasuhiro Kiyota',
     author_email='yasuhiroki.duck@gmail.com',
```

という形で読み込むか、setup.pyの方でversion 指定しておいて

```
-- a/aozoracli/version.py
+++ b/aozoracli/version.py
@@ -1 +1,3 @@
-__version__ = "0.0.1"
+import pkg_resources
+__version__ = pkg_resources.require("aozora-cli")[0].version
```

という形で、その情報を逆にversion.pyの方で読み込むかかなと思います。

如何でしょうか。

**Comment by yasuhiroki** [comment]
ご連絡ありがとうございます。
clickがインスール済みな環境で試していたので気づけなかったようです・・・すみません（汗
週末に確認してみますが、
`setup.py` にバージョン書いてしまう方が分かりやすくて良さそうです。

**Comment by yasuhiroki** [comment]
51e46bc9007b5a581e022de9106765fcf2fc8807 で修正しました。
