### ISSUE TITLE
aozora book > xxx.txt　のとき　エラーが発生しました

### ISSUE THREAD

**Issue by xisang233** [aozorahack/aozora-cli#22]
普通にターミナルで
> aozora  book

の時は、結果が出てくるんです。
しかし
> aozora book > a.txt

で、結果を保存したいとき、ダメでした。
osは　ubuntu14.04とdebian 8.6。また、pip install でインストールしたのです。

エラー：
Traceback (most recent call last):
  File "/usr/local/bin/aozora", line 10, in <module>
    sys.exit(main())
  File "/usr/local/bin/aozora", line 7, in main
    return aozoracli.cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/aozoracli/cli.py", line 38, in books
    _print(res, output)
  File "/usr/local/lib/python2.7/dist-packages/aozoracli/cli.py", line 79, in _print
    print(output)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 34-36: ordinal not in range(128)

**Comment by xisang233** [comment]
ネットで調べてみたら、cli.pyにこれを付け加えればいいです
> import sys
reload(sys)
sys.setdefaultencoding( "utf-8" )

ただ、７１行目には日本語があって、削除しないと
> SyntaxError: Non-ASCII character '\xe3' in file /usr/local/lib/python2.7/dist-packages/aozoracli/cli.py on line 71, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

が発生してしまいます。

**Comment by xisang233** [comment]
Python2にはこのような問題が多いですね。Python3でやり直せば、、、こういった問題が起こさないでしょう。。。(大変お手数ですが。。。)

**Comment by yasuhiroki** [comment]
ご報告ありがとうございます。
時間のある時に調べてみます。

**Comment by yasuhiroki** [comment]
@xisang233 0.0.3 で修正しました。
手元では python2, python3 両方で動作しました。
